"""final_initial_schema

Revision ID: ea525aa66ccc
Revises: 
Create Date: 2026-03-29 15:34:50.792787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea525aa66ccc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('public_key', sa.String(length=100), nullable=False),
    sa.Column('secret_key', sa.String(length=100), nullable=False),
    sa.Column('allowed_origins', sa.JSON(), nullable=True),
    sa.Column('widget_color', sa.String(length=20), nullable=True),
    sa.Column('widget_placeholder', sa.String(length=255), nullable=True),
    sa.Column('widget_position', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_public_key'), 'tenants', ['public_key'], unique=True)
    op.create_index(op.f('ix_tenants_secret_key'), 'tenants', ['secret_key'], unique=True)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('tenant_databases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('db_type', sa.String(length=20), nullable=True),
    sa.Column('db_host', sa.String(length=255), nullable=False),
    sa.Column('db_port', sa.Integer(), nullable=True),
    sa.Column('db_name', sa.String(length=255), nullable=False),
    sa.Column('db_user_enc', postgresql.BYTEA(), nullable=False),
    sa.Column('db_password_enc', postgresql.BYTEA(), nullable=False),
    sa.Column('db_ssl', sa.Boolean(), nullable=True),
    sa.Column('allowed_tables', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('schema_cache', sa.JSON(), nullable=True),
    sa.Column('schema_synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('tenant_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('qdrant_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_documents_tenant_id'), 'tenant_documents', ['tenant_id'], unique=False)
    op.create_table('tenant_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_files_id'), 'tenant_files', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_files_tenant_id'), 'tenant_files', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_files_tenant_id'), table_name='tenant_files')
    op.drop_index(op.f('ix_tenant_files_id'), table_name='tenant_files')
    op.drop_table('tenant_files')
    op.drop_index(op.f('ix_tenant_documents_tenant_id'), table_name='tenant_documents')
    op.drop_table('tenant_documents')
    op.drop_table('tenant_databases')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_secret_key'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_public_key'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
